class RouteStops {
  static const List route_n1_eastbound = [
    'Centennial Circle',
    'Elesmere Westbound @ Moringside',
    'Morningside Northbound @ Military Trail',
    'Ellesmere Eastbound @ Military Trail',
    'Ellesmere Eastbound @ Meadowvale',
    'Kingston Eastbound @ Port Union',
    'Kingston Eastbound @ Altona',
    'Kingston Eastbound @ Rougemount',
    'Kingston Eastbound @ Rosebank',
    'Kingston Eastbound @ Steeple Hill',
    'Kingston Eastbound @ Whites',
    'Eastbound @ 817 Kingston',
    'Kingston Eastbound @ Fairport',
    'Kingston Eastbound @ Dixie',
    'Kingston Eastbound @ Walnut',
    'Kingston Eastbound @ Liverpool',
    'Kingston Eastbound @ Glenanna',
    'Kingston Eastbound @ Valley Farm',
    'Kingston Eastbound @ Brock Road',
    'Kingston Eastbound @ Bainbridge',
    'Kingston Eastbound @ Notion',
    'Kingston Eastbound @ Elizabeth',
    'Eastbound @ 625 Kingston',
    'Kingston Eastbound @ Mill',
    'Kingston Eastbound @ Westney',
    'Kingston Eastbound @ Ritchie',
    'Eastbound @ 113 Kingston',
    'Kingston Eastbound @ Harwood',
    'Eastbound @ 69 Kingston',
    'Kingston Eastbound @ Salem',
    'Eastbound @ 257 Kingston Road East',
    'Kingston Eastbound @ Wicks',
    'Kingston Eastbound @ Alexanders Crossing',
    'Kingston Eastbound @ Audley',
    'Kingston Eastbound @ Lake Ridge',
    'Dundas Eastbound @ Halls',
    'Dundas Eastbound @ Des Newman',
    'Dundas Eastbound @ White Oaks',
    'Dundas Eastbound @ Jeffery',
    'Dundas Eastbound @ Wellington',
    'Dundas Eastbound @ Annes',
    'Dundas Eastbound @ King',
    'Dundas Eastbound @ Brock Street',
    'Dundas Eastbound @ Hickory',
    'Dundas Eastbound @ Lupin',
    'Dundas Eastbound @ Craydon',
    'Dundas Eastbound @ Hopkins',
    'Dundas Eastbound @ Glen Hill',
    'Dundas Eastbound @ Thickson',
    'Dundas Eastbound @ Kathleen',
    'Dundas Eastbound @ Kendalwood',
    'King Eastbound @ Thornton',
    'King Eastbound @ Waverly',
    'King Eastbound @ Stevenson',
    'King Eastbound @ Gibbons',
    'King Eastbound @ Warren',
    'King Eastbound @ Midtown',
    'King Eastbound @ Centre',
    'King Eastbound @ Simcoe',
    'King Eastbound @ Mary',
    'King Eastbound @ Drew',
    'King Eastbound @ Rowe',
    'King Eastbound @ Central Park',
    'King Eastbound @ Cadillac',
    'King Eastbound @ Wilson',
    'King Eastbound @ Farewell',
    'King Eastbound @ Riverside',
    'Harmony Northbound @ King',
    'Harmony Northbound @ Regent',
    'Harmony Northbound @ Eastbourne',
    'Harmony Northbound @ Adelaide',
    'Northbound @ 443 Harmony',
    'Harmony Northbound @ Rossland (South Side Stop)',
    'Harmony Northbound @ Rossland (North Side Stop)',
    'Harmony Northbound @ Corbetts',
    'Harmony Northbound @ Storie',
    'Harmony Northbound @ Beatrice',
    'Harmony Northbound @ Swiss',
    'Harmony Northbound @ Grand Ridge',
    'Harmony Northbound @ Taunton (South Side Stop)',
    'Harmony Northbound @ Taunton (North Side Stop)',
    'Harmony Terminal'
  ];

  static const List route_n1_westbound = [
    'Harmony Terminal',
    'Harmony Terminal Southbound @ Taunton',
    'Harmony Southbound @ Taunton',
    'Harmony Southbound @ Grand Ridge',
    'Harmony Southbound @ Swiss',
    'Harmony Southbound @ Beatrice',
    'Harmony Southbound @ Storie',
    'Harmony Southbound @ Corbetts',
    'Harmony Southbound @ Rossland',
    'Harmony Southbound @ Glebe',
    'Harmony Southbound @ Adelaide',
    'Harmony Southbound @ Eastbourne',
    'Harmony Southbound @ Regent',
    'Harmony Southbound @ King',
    'King Westbound @ Harmony',
    'Bond Northbound @ Riverside',
    'Bond Westbound @ Claymore (East Side Stop)',
    'Bond Westbound @ Claymore (West Side Stop)',
    'Bond Westbound @ Cadillac',
    'Bond Westbound @ Patricia',
    'Bond Westbound @ Oshawa Boulevard',
    'Bond Westbound @ Ritson',
    'Bond Westbound @ Mary',
    'Bond Westbound @ Simcoe',
    'Bond Westbound @ Centre',
    'Bond Westbound @ Arena',
    'Bond Westbound @ Park',
    'Bond Westbound @ Gibbons',
    'Bond Westbound @ Stevenson',
    'King Westbound @ Waverly',
    'King Westbound @ Thornton',
    'Dundas Westbound @ Garrard',
    'Dundas Westbound @ Kathleen',
    'Dundas Westbound @ Thickson',
    'Dundas Westbound @ Bowman',
    'Dundas Westbound @ Anderson',
    'Dundas Westbound @ Craydon',
    'Dundas Westbound @ Garden',
    'Dundas Westbound @ Pine',
    'Dundas Westbound @ Brock Street',
    'Dundas Westbound @ Euclid',
    'Dundas Westbound @ Cochrane',
    'Dundas Westbound @ Wellington',
    'Dundas Westbound @ Mcquay',
    'Dundas Westbound @ White Oaks',
    'Dundas Westbound @ Des Newman',
    'Dundas Westbound @ Halls',
    'Kingston Westbound @ Lake Ridge',
    'Kingston Westbound @ Audley',
    'Kingston Westbound @ Alexanders Crossing',
    'Kingston Westbound @ Wicks',
    'Kingston Westbound @ Salem',
    'Westbound @ 84 Kingston',
    'Kingston Westbound @ Harwood',
    'Westbound @ 132 Kingston',
    'Kingston Westbound @ Chapman',
    'Kingston Westbound @ Westney',
    'Kingston Westbound @ Mill',
    'Kingston Westbound @ Church',
    'Kingston Westbound @ Elizabeth',
    'Kingston Westbound @ Notion',
    'Kingston Westbound @ Bainbridge',
    'Kingston Westbound @ Brock Road',
    'Kingston Westbound @ Valley Farm',
    'Kingston Westbound @ Glenanna',
    'Kingston Westbound @ Liverpool',
    'Kingston Westbound @ Walnut',
    'Kingston Westbound @ Dixie',
    'Kingston Westbound @ Fairport',
    'Westbound @ 804 Kingston',
    'Kingston Westbound @ Delta',
    'Kingston Westbound @ Whites',
    'Kingston Westbound @ Steeple Hill',
    'Kingston Westbound @ Rosebank',
    'Kingston Westbound @ Rougemount',
    'Kingston Westbound @ Altona',
    'Kingston Westbound @ Sheppard',
    'Ellesmere Westbound @ Meadowvale',
    'Ellesmere Westbound @ Military Trail',
    'Elesmere Westbound @ Moringside',
    'Morningside Northbound @ Military Trail',
    'Centennial Circle'
  ];

  static const List route_101_clockwise = [
    'Pickering Station',
    'Bayly Eastbound @ Krosno',
    'Bayly Eastbound @ Sandy Beach',
    'Bayly Eastbound @ Alliance',
    'Bayly Eastbound @ Salk',
    'Bayly Eastbound @ Brock Road',
    'Brock Road Southbound @ Orangebrook',
    'Brock Road Southbound @ Quigley',
    'Clements Eastbound @ Brock Road',
    'Eastbound @ 1845 Clements',
    'Eastbound @ 1885 Clements',
    'Clements Eastbound @ Squires Beach',
    'Squires Beach Southbound @ Clements',
    'Squires Beach Southbound @ Mckay',
    'Westbound @ 850 Mckay',
    'Southbound @ 770 Mckay',
    'Montgomery Park Westbound @ Brock Road',
    'Montgomery Park Westbound @ Opg Pickering',
    'Sandy Beach Northbound @ Montgomery Park',
    'Sandy Beach Northbound @ Parkham',
    'Lublin Northbound @ Balaton',
    'Alyssum Westbound @ Krosno',
    'Krosno Westbound @ Modlin',
    'Liverpool Northbound @ Haller',
    'Liverpool Northbound @ Patmore',
    'Liverpool Northbound @ Bayly',
    'Liverpool Northbound @ Pickering Parkway',
    'Kingston Eastbound @ Liverpool',
    'Glenanna Southbound @ The Esplanade (South Side Stop)',
    'Pickering Parkway Terminal Platform B13',
    'Liverpool Southbound @ Pickering Parkway',
    'Pickering Station'
  ];

  static const List route_101_countercw = [
  'Pickering Station',
  'Liverpool Northbound @ Pickering Parkway',
  'Kingston Eastbound @ Liverpool,'
  'Glenanna Southbound @ The Esplanade (South Side Stop)',
  'Pickering Parkway Terminal Platform B13',
  'Liverpool Southbound @ Pickering Parkway',
  'Liverpool Southbound @ Tatra',
  'Liverpool Southbound @ East Shore Community Centre',
  'Liverpool Southbound @ Patmore',
  'Liverpool Southbound @ Haller',
  'Southbound @ 725 Krosno',
  'Krosno Eastbound @ Annland',
  'Krosno Eastbound @ Modlin',
  'Alyssum Eastbound @ Lublin',
  'Lublin Southbound @ Balaton',
  'Parkham Eastbound @ Sandy Beach',
  'Southbound @ 675 Sandy Beach Road',
  'Montgomery Park Eastbound @ Opg Pickering',
  'Montgomery Park Eastbound @ Brock Road',
  'Mckay Northbound @ Montgomery Park',
  'Mckay Eastbound @ Squires Beach',
  'Squires Beach Northbound @ Mckay',
  'Northbound @ 1111 Squires Beach',
  'Clements Westbound @ Squires Beach',
  'Westbound @ 1850 Clements',
  'Westbound @ 1768 Clements',
  'Clements Westbound @ Brock Road',
  'Brock Road Northbound @ Quigley',
  'Brock Road Northbound @ Orangebrook',
  'Bayly Westbound @ Brock Road',
  'Bayly Westbound @ Salk',
  'Bayly Westbound @ Alliance',
  'Bayly Westbound @ Sandy Beach',
  'Bayly Westbound @ Krosno',
  'Westbound @ 1400 Bayly',
  'Pickering Station'
  ];

}